[tool.poetry]
name = "SUPERHEX"
version = "1.0.0"
description = "Supercell Optimization for Heisenberg Exchange Calculations"
authors = ["Mojtaba Alaei"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
